$configs = $HOME/.config/hypr/configs

source=$configs/appearance.conf
source=$configs/env.conf
source=$configs/exec.conf
source=$configs/input.conf
source=$configs/keybinds.conf

# monitors.conf and workspaces.conf managed by nwg-displays (writable)
source=~/.config/hypr/monitors.conf
source=~/.config/hypr/workspaces.conf


# Example per-device config
# See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = brave-render-unfocused
    match:class = ^(brave-browser)$
    render_unfocused = on
}
