#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = waybar

exec-once = eww daemon
exec-once = sh -c 'sleep 1 && eww open corners'
exec-once = sh -c 'sleep 1 && eww open corners_alt'

exec-once = dunst

exec-once = hyprpaper
exec-once = $scriptsDir/wallpaper-restore.sh

exec-once = sudo asusctl slash light off
