#############
### INPUT ###
#############

# https://wiki.hyprland.org/Configuring/Variables/#input
input {
    kb_layout = us,th
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle,ctrl:nocaps,rightalt:backspace
    kb_rules =

    follow_mouse = 0

    sensitivity = -0.15 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        scroll_factor = 0.25
        middle_button_emulation = false
    }
}

################
### GESTURES ###
################

gesture = 2, pinchout, cursorZoom
